name: Deploy to EC2

on:
  push:
    branches:
      - main   # Trigger deployment on push to the main branch

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Deploy to EC2 via SSH
        uses: appleboy/ssh-action@v1.0.3
        with:
          host: ${{ secrets.EC2_HOST }}
          username: ${{ secrets.EC2_USER }}
          key: ${{ secrets.EC2_SSH_KEY }}
          port: 22
          script: |
            # Remove old files
            sudo rm -rf /var/www/html/*
            
            # Clone the latest version of the repo
            git clone https://github.com/Sandesh-Gadal/mini_finance.git /var/www/html
            
            # Set appropriate permissions
            sudo chown -R nginx:nginx /var/www/html
            sudo chmod -R 755 /var/www/html
            
            # Reload Nginx to apply changes
            sudo systemctl reload nginx
